#!/usr/bin/env python3
"""
count_evds_per_subtask.py — refresh the per-(factor→outcome) evidence-summary table + EP strength tags.

WHAT
    Maintains the cross-paper evidence-summary index (Evidence Summary.md) and keeps each
    EvidencePattern's strength tag honest. The automatic columns are counts only; the interpretive
    columns are left for a human.

HOW
    1. Read every EVD's facet fields (primary languageConcordanceFactor × healthOutcome) and its paper
       (@citekey from the filename); bucket distinct EVDs and papers per (factor → outcome) subtask.
    2. From relations.json, gather each EP's supporting EVDs and their distinct papers, and rewrite the
       EP note's `ep/strength/<N>-papers` tag to match (only when an existing tag is present).
    3. Emit Evidence Summary.md: one row per subtask with #EVDs / #papers filled in, and
       Direction / Effect size / Strength left as _TODO_ (human-synthesized, propose-don't-commit).

INPUT   Discourse Graph/Evidence/EVD - *.md (facets); EvidencePatterns/*.md; relations.json.
OUTPUT  Evidence Summary.md (vault root) + in-place EP `ep/strength` tag edits + a console summary.

INVARIANTS / NOTES
    - Propose-don't-commit: Direction/Effect size/Strength stay TODO; only counts are written.
    - The only mutation is the numeric `ep/strength/<N>-papers` tag; EPs without one are left for the
      author to add.
    - --dry-run reports without writing the summary or touching any EP note.

USAGE
    python3 utils/count_evds_per_subtask.py            # write summary + refresh EP strength tags
    python3 utils/count_evds_per_subtask.py --dry-run  # report only, no file changes

Design decisions, limitations, and the "smarter later" roadmap: Pipeline/count_evds_per_subtask.md
"""

import argparse
import json
import re
from collections import defaultdict
from pathlib import Path

import yaml

REL_SUPPORTS = "relation_BO5BtVVpJGrw70jTCTznm"
EP_TYPE = "node_r2JRW9jgphgmMpz5mN7eG"
EVD_TYPE = "node_huDx8FGfNSGQyongW5rk-"


def split(path: Path):
    c = path.read_text(encoding="utf-8")
    m = re.match(r"^---\s*\n(.*?)\n---\s*\n?(.*)$", c, re.DOTALL)
    if not m:
        return {}, "", c
    return (yaml.safe_load(m.group(1)) or {}), m.group(1), m.group(2)


def first(v):
    return (v[0] if v else None) if isinstance(v, list) else v


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--dry-run", action="store_true")
    args = ap.parse_args()

    root = Path(__file__).parent.parent
    dg = root / "Discourse Graph"

    # EVDs
    evd_by_iid = {}
    subtasks = defaultdict(lambda: {"evds": set(), "papers": set()})
    for f in (dg / "Evidence").glob("EVD - *.md"):
        fm, _, _ = split(f)
        iid = fm.get("nodeInstanceId")
        paper = re.search(r"@[A-Za-z][\w\-]+", f.stem)
        paper = paper.group(0) if paper else None
        evd_by_iid[iid] = paper
        fct, out = first(fm.get("languageConcordanceFactor")), first(fm.get("healthOutcome"))
        if fct and out:
            subtasks[(fct, out)]["evds"].add(iid)
            if paper:
                subtasks[(fct, out)]["papers"].add(paper)

    # EP strength from relations.json
    rels = json.loads((root / "relations.json").read_text())["relations"].values()
    ep_support = defaultdict(set)  # ep_iid -> set(paper)
    ep_files = {}
    for f in (dg / "EvidencePatterns").glob("*.md") if (dg / "EvidencePatterns").exists() else []:
        fm, _, _ = split(f)
        ep_files[fm.get("nodeInstanceId")] = f
    for e in rels:
        if e["type"] == REL_SUPPORTS and e["destination"] in ep_files and e["source"] in evd_by_iid:
            p = evd_by_iid[e["source"]]
            if p:
                ep_support[e["destination"]].add(p)

    # refresh EP strength tags
    updated = []
    for ep_iid, f in ep_files.items():
        n = len(ep_support.get(ep_iid, set()))
        if n == 0:
            continue
        text = f.read_text(encoding="utf-8")
        new = re.sub(r"ep/strength/\d+-papers", f"ep/strength/{n}-papers", text)
        if f"ep/strength/{n}-papers" not in text:  # no existing tag → leave as-is (author adds)
            pass
        if new != text and not args.dry_run:
            f.write_text(new, encoding="utf-8")
            updated.append((f.stem, n))
        elif new != text:
            updated.append((f.stem, n))

    # write summary table
    rows = sorted(subtasks.items(), key=lambda kv: len(kv[1]["papers"]), reverse=True)
    lines = ["# Evidence summary (by factor → outcome)", "",
             "> Generated by `utils/count_evds_per_subtask.py`. Counts are automatic; **Direction / Effect size /",
             "> Evidence strength are human-synthesized** (propose-don't-commit).", "",
             "| Subtask (factor → outcome) | #EVDs | #papers | Direction | Effect size | Strength |",
             "| --- | ---: | ---: | --- | --- | --- |"]
    for (fct, out), d in rows:
        lines.append(f"| {fct} → {out} | {len(d['evds'])} | {len(d['papers'])} | _TODO_ | _TODO_ | _TODO_ |")
    if not args.dry_run:
        (root / "Evidence Summary.md").write_text("\n".join(lines), encoding="utf-8")

    print(f"Subtasks: {len(subtasks)} | EVDs with facets: {sum(len(d['evds']) for d in subtasks.values())}")
    for (fct, out), d in rows[:12]:
        print(f"  {len(d['papers'])}p / {len(d['evds'])}e   {fct} → {out}")
    if updated:
        print("\nEP strength refreshed:")
        for name, n in updated:
            print(f"  {n}-papers  {name[:70]}")
    print(f"\n{'(dry-run) ' if args.dry_run else ''}Wrote: Evidence Summary.md")


if __name__ == "__main__":
    main()
