#!/usr/bin/env python3
"""
propose_eps.py — propose candidate EvidencePatterns as a human accept/reject CHECKLIST.
Governance: this script never writes final EP files. It clusters existing EVD nodes that share a
factor×outcome facet and come from ≥2 distinct papers, and emits `EP Proposals.md`.

Heuristic: group EVDs by (primary languageConcordanceFactor × primary healthOutcome); within each
group needing ≥2 papers, report embedding coherence and flag EVDs already bundled into an EP.

Usage:
    python3 utils/propose_eps.py
    python3 utils/propose_eps.py --min-papers 2 --no-embeddings
"""

import os
os.environ.setdefault("KMP_DUPLICATE_LIB_OK", "TRUE")
os.environ.setdefault("OMP_NUM_THREADS", "1")

import argparse
import json
import re
from collections import defaultdict
from pathlib import Path

import numpy as np
import yaml

REL_SUPPORTS = "relation_BO5BtVVpJGrw70jTCTznm"
EP_TYPE = "node_r2JRW9jgphgmMpz5mN7eG"
EVD_TYPE = "node_huDx8FGfNSGQyongW5rk-"


def split(path: Path):
    c = path.read_text(encoding="utf-8")
    m = re.match(r"^---\s*\n(.*?)\n---\s*\n?(.*)$", c, re.DOTALL)
    if not m:
        return {}, c
    try:
        return yaml.safe_load(m.group(1)) or {}, m.group(2)
    except yaml.YAMLError:
        return {}, m.group(2)


def first(v):
    if isinstance(v, list):
        return v[0] if v else None
    return v


def description(body: str) -> str:
    m = re.search(r"##\s*Description\s*\n(.*?)(?:\n##\s|\Z)", body, re.DOTALL)
    txt = m.group(1) if m else body
    txt = re.sub(r"!\[\[[^\]]*\]\]", "", txt)        # drop embeds
    txt = re.sub(r"^>.*$", "", txt, flags=re.MULTILINE)  # drop blockquotes (quotes)
    return re.sub(r"\s+", " ", txt).strip()


def embed(texts):
    try:
        from sentence_transformers import SentenceTransformer
        m = SentenceTransformer("all-MiniLM-L6-v2")
        return np.asarray(m.encode(texts, normalize_embeddings=True, show_progress_bar=False))
    except Exception as e:
        print(f"  embeddings unavailable ({e})")
        return None


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--min-papers", type=int, default=2)
    ap.add_argument("--no-embeddings", action="store_true")
    args = ap.parse_args()

    root = Path(__file__).parent.parent
    dg = root / "Discourse Graph"

    # EVDs already bundled into an EP (instanceId set)
    rels = json.loads((root / "relations.json").read_text())["relations"].values()
    ep_iids = {f.stem: None for f in (dg / "EvidencePatterns").glob("*.md")} if (dg / "EvidencePatterns").exists() else {}
    # map instanceId->isEP via frontmatter
    iid_type = {}
    evds = []
    for f in (dg / "Evidence").glob("EVD - *.md"):
        fm, body = split(f)
        iid = fm.get("nodeInstanceId")
        iid_type[iid] = "EVD"
        paper = (re.search(r"@[A-Za-z][\w\-]+", f.stem) or [None])
        paper = re.search(r"@[A-Za-z][\w\-]+", f.stem)
        evds.append({
            "name": f.stem, "iid": iid,
            "paper": paper.group(0) if paper else None,
            "factor": first(fm.get("languageConcordanceFactor")),
            "outcome": first(fm.get("healthOutcome")),
            "text": f.stem + ". " + description(body),
        })
    for f in (dg / "EvidencePatterns").glob("*.md"):
        fm, _ = split(f)
        iid_type[fm.get("nodeInstanceId")] = "EP"
    in_ep = set()
    for e in rels:
        if e["type"] == REL_SUPPORTS and iid_type.get(e["destination"]) == "EP" and iid_type.get(e["source"]) == "EVD":
            in_ep.add(e["source"])

    emb = None if args.no_embeddings else embed([e["text"] for e in evds])
    idx = {e["iid"]: i for i, e in enumerate(evds)}

    groups = defaultdict(list)
    for e in evds:
        if e["factor"] and e["outcome"]:
            groups[(e["factor"], e["outcome"])].append(e)

    proposals = []
    for (fct, out), members in groups.items():
        papers = {m["paper"] for m in members if m["paper"]}
        if len(papers) < args.min_papers:
            continue
        coh = None
        if emb is not None:
            vecs = np.array([emb[idx[m["iid"]]] for m in members])
            cen = vecs.mean(axis=0)
            coh = round(float(np.mean(vecs @ cen / (np.linalg.norm(vecs, axis=1) * np.linalg.norm(cen) + 1e-9))), 3)
        covered = sum(1 for m in members if m["iid"] in in_ep)
        proposals.append({"factor": fct, "outcome": out, "members": members,
                          "papers": len(papers), "coh": coh, "covered": covered})

    proposals.sort(key=lambda p: (p["papers"], p["coh"] or 0), reverse=True)

    lines = ["# EvidencePattern proposals", "",
             "> Generated by `utils/propose_eps.py`. **Propose, don't commit** — tick to accept, then author the EP node.",
             ""]
    for n, p in enumerate(proposals, 1):
        status = "  ⟢ already partly bundled in an EP" if p["covered"] else ""
        lines.append(f"## {n}. {p['factor']} → {p['outcome']}  ({p['papers']} papers · {len(p['members'])} EVDs · coherence {p['coh']}){status}")
        lines.append(f"- [ ] **Provisional EP:** _{p['factor']} relates to {p['outcome'].lower()}_  (pattern statement to refine)")
        for m in p["members"]:
            mark = "✓in-EP " if m["iid"] in in_ep else ""
            lines.append(f"    - {mark}[[{m['name']}]]")
        lines.append("")
    (root / "EP Proposals.md").write_text("\n".join(lines), encoding="utf-8")

    print(f"EVDs: {len(evds)} | already in an EP: {len(in_ep)}")
    print(f"Candidate EP buckets (≥{args.min_papers} papers): {len(proposals)}")
    for p in proposals:
        print(f"  {p['papers']}p/{len(p['members'])}e coh={p['coh']}  {p['factor']} → {p['outcome']}"
              + (f"  ({p['covered']} EVDs already in an EP)" if p["covered"] else ""))
    print("\nWrote: EP Proposals.md")


if __name__ == "__main__":
    main()
